#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Správné kuličky pro lekci 4 - Skutečné bohatství
lesson4_kulicky = [
    "finanční nouzi",
    "uvěření v život v nouzi a nedostatku",
    "být smolařem",
    "přesvědčení, že vždycky prohraji",
    "přesvědčení, že peníze jsou zlo a prokleté",
    "přesvědčení, že peníze kazí charakter člověka",
    "přesvědčení, že peníze dělají veškeré zlo na světě",
    "neschopnost peníze přijmout do svého života",
    "odpor ke konání",
    "neschopnost vidět možnosti dalšího výdělku",
    "přesvědčení, že peníze jsou pokušení",
    "přesvědčení, že peníze dělají člověka špatným a lačným",
    "přesvědčení, že čím je člověk bohatší, tím je lačnější",
    "peníze smrdí",
    "přesvědčení, že poctivou prací nezbohatnu",
    "přesvědčení, že lidé nemají peníze",
    "přesvědčení, že peníze se vydělávají těžkou prací, potem a krví",
    "že vydělávání peněz je jen dřina",
    "odpor k přijímání peněz",
    "zákaz používat peníze pro realizaci svých úmyslů a záměrů",
    "tavení toku peněz do svého života",
    "nevědomost jak peníze získávat a disponovat s nimi",
    "stagnace ve finančním vývoji",
    "vše, co mne brání využívat své bohatství ve svém životě",
    "přesvědčení, že s dospíváním dětí rostou výdaje",
    "podporování vlastní hlouposti a slabosti",
    "komplexy méněcennosti, když nemám velké bohatství",
    "přesvědčení, že jen peníze mne pomůžou k uskutečnění vlastních záměrů",
    "být otrokyní peněz",
    "že mám peníze jako drogu",
    "strach z nízkého platu",
    "strach z výpovědi",
    "strach ze ztráty peněz",
    "nechuť konat a žít v tomto světě",
    "přesvědčení, že náš svět je hrozný",
    "že peníze jsou smyslem a jediným záměrem života",
    "podřizování všeho k dosažení hmotného blahobytu",
    "nezastavitelná závod v honbě o peníze",
    "strach z chamtivosti",
    "že po vydělání peněz brzy cítím zase nedostatek",
    "stálý neklid ohledně peněz",
    "lpění na penězích",
    "odpor k vychloubání penězi od druhých",
    "opovrhování měnou mého národa",
    "zavrhování peněz",
    "přesvědčení, že peníze mne nezajímají",
    "paniku z finančních potíží",
    "strach z velkého jmění",
    "odsuzování vlády a politiků",
    "strašící myšlenky ohledně peněz",
    "strach ze ztráty majetku",
    "zatvrzené srdce ziskuchtivostí",
    "nezáviděhodný finanční stav",
    "lítost nad chudobou druhých",
    "pocit prázdné peněženky",
    "strach, že nemám za co koupit potřebné věci",
    "vyhazování peněz za věci, které nepotřebuji",
    "přesvědčení, že svět je omezený v hojnosti peněz pro všechny",
    "strach z malých důchodů",
    "strach, že nemám dostatek našetřeno",
    "strach, že se o mne a mou rodinu nemá kdo postarat",
    "závist jako překážka k bohatství",
    "strach z finanční závislosti na druhých",
    "že mne finanční závazky zničí",
    "finanční břemeno",
    "negativní obraz práce mých rodičů",
    "apatii k penězům",
    "lenivost vydělat peníze",
    "strach z nezaměstnanosti",
    "strach ze ztráty zaměstnání",
    "odpor k sociálním dávkám",
    "strach z ostudy, že nejsem dost výdělečný člověk",
    "přesvědčení, že odchod do důchodu je tragédie",
    "strach ze zpožděných plateb",
    "přesvědčení, že velké množství peněz vyřeší problémy",
    "přesvědčení, že vydělávání peněz je vždy na úkor rodiny",
    "ztráta naděje na splacení dluhu",
    "strach ze zadlužení"
]

print(f"Lesson 4 has {len(lesson4_kulicky)} kulicky")
print("First 5 kulicky:")
for i, k in enumerate(lesson4_kulicky[:5], 1):
    print(f"  {i}. {k}")